### ISSUE TITLE
bug: rag fails with too many open files. 

### ISSUE THREAD

**Issue by MarlNox** [open-webui/open-webui#1059]
# Bug Report

## Description
Using RAG on many documents at once makes the system fail - with the only solution being a restart.

**Bug Summary:**
Currently using Anthropic to run RAG.

Using _openwebui_ consumes all my 24gb VRAM when trying to both RAG all documents and running the Ollama model. I thought that removing the requirements of running the LLM would essentially fix the issue, but another issue materialized. 

When searching across all the documents #collection to find the relevant RAG snippets the system fails. First the error materializes in the front end and the backend by providing this error: 

```
Number of requested results 4 is greater than number of elements in index 1, updating n_results = 1
Number of requested results 4 is greater than number of elements in index 3, updating n_results = 3
Number of requested results 4 is greater than number of elements in index 1, updating n_results = 1
Number of requested results 4 is greater than number of elements in index 3, updating n_results = 3
Number of requested results 4 is greater than number of elements in index 2, updating n_results = 2
Number of requested results 4 is greater than number of elements in index 2, updating n_results = 2
INFO:     79.106.113.250:0 - "POST /rag/api/v1/query/collection HTTP/1.1" 200 OK
INFO:     79.106.113.250:0 - "GET /rag/api/v1/template HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/home/x/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
  File "/home/x/anaconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
  File "/home/x/anaconda3/lib/python3.10/socket.py", line 955, in getaddrinfo
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
  File "/home/x/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 404, in _make_request
  File "/home/x/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
  File "/home/x/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
  File "/home/x/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f64f9879de0>: Failed to establish a new connection: [Errno 22] Invalid argument
```

then 

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/anaconda3/lib/python3.10/site-packages/litellm/main.py", line 283, in acompletion
  File "/home/x/anaconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
  File "/home/x/anaconda3/lib/python3.10/site-packages/litellm/utils.py", line 2605, in wrapper
  File "/home/x/anaconda3/lib/python3.10/site-packages/litellm/utils.py", line 2508, in wrapper
  File "/home/x/anaconda3/lib/python3.10/site-packages/litellm/main.py", line 1907, in completion
  File "/home/x/anaconda3/lib/python3.10/site-packages/litellm/utils.py", line 7662, in exception_type
  File "/home/x/anaconda3/lib/python3.10/site-packages/litellm/utils.py", line 7630, in exception_type
litellm.exceptions.APIConnectionError: HTTPSConnectionPool(host='api.anthropic.com', port=443): Max retries exceeded with url: /v1/complete (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f64f9879de0>: Failed to establish a new connection: [Errno 22] Invalid argument'))

```
and then this error: 
```
File "/home/x/anaconda3/lib/python3.10/site-packages/litellm/utils.py", line 7662, in exception_type
File "/home/x/anaconda3/lib/python3.10/site-packages/litellm/utils.py", line 6623, in exception_type
AttributeError: 'APIConnectionError' object has no attribute 'response'
```

After the error occurs, opening a new chat and trying to converse with the LLM,  without using RAG at all, the following error appears, and doesnt resolve itself until i restart oopen-webui. Runnign further queries, without restarting, fails and this error comes up in the backend: 

```

anconda3/lib/python3.10/site-packages/litellm/utils.py", line 3039, in wrapper_async
  File "/home/x/anaconda3/lib/python3.10/site-packages/litellm/utils.py", line 2882, in wrapper_async
  File "/home/x/anaconda3/lib/python3.10/site-packages/litellm/main.py", line 291, in acompletion
  File "/home/x/anaconda3/lib/python3.10/site-packages/litellm/utils.py", line 7662, in exception_type
  File "/home/x/anaconda3/lib/python3.10/site-packages/litellm/utils.py", line 6623, in exception_type
AttributeError: 'APIConnectionError' object has no attribute 'response'
INFO:     79.106.113.250:0 - "POST /litellm/api/v1/chat/completions HTTP/1.1" 500 Internal Server Error
INFO:     79.106.113.250:0 - "POST /api/v1/chats/41727b5c-e6aa-4858-9d4f-5c473f6d1c67 HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44168 - "GET /_app/immutable/nodes/7.72f9e4c8.js HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/x/anaconda3/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
  File "/home/x/anaconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in _call_
  File "/home/x/anaconda3/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in _call_
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/applications.py", line 123, in _call_
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in _call_
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in _call_
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/middleware/base.py", line 192, in _call_
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/responses.py", line 257, in _call_
  File "/home/x/anaconda3/lib/python3.10/site-packages/anyio/backends/_asyncio.py", line 597, in __aexit_
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/responses.py", line 260, in wrap
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/middleware/base.py", line 217, in stream_response
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/responses.py", line 249, in stream_response
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/middleware/base.py", line 181, in body_stream
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in _call_
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in _call_
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 758, in _call_
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/routing.py", line 487, in handle
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/staticfiles.py", line 104, in _call_
  File "/home/x/anaconda3/lib/python3.10/site-packages/starlette/responses.py", line 346, in _call_
  File "/home/x/anaconda3/lib/python3.10/site-packages/anyio/_core/_fileio.py", line 193, in open_file
  File "/home/x/anaconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
  File "/home/x/anaconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
  File "/home/x/anaconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
OSError: [Errno 24] Too many open files: '/home/x/Desktop/brainllm-openui-main/build/_app/immutable/nodes/7.72f9e4c8.js
```

**Steps to Reproduce:**
Run a RAG query using a large amount of documents. 

**Expected Behavior:**
The Agent should provide a response as per the LLM's response, based on the extracted text snippets during RAG. 

**Actual Behavior:**
I try to run RAG queries on all documents (rather than one or a small collection of documents) and get a response. 

## Environment

- **Operating System:** [Ubuntu 20.04]

## Reproduction Details

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I have reviewed the troubleshooting.md document.

## Installation Method
Install without docker, directly on my Ubuntu. 

## Additional Information
No issues on smaller RAG context queries.

**Comment by MarlNox** [comment]
The new version seems to not have this issue. I just tried it with a large number of documents. 
I will experiment more with it and report back.

**Comment by MarlNox** [comment]
Issue reappeared by itself. No changes were made.

**Comment by MarlNox** [comment]
After some tinkering the solution is:to Increase the File Descriptor Limit 

For me a temporary fix was ulimit -n 4096. Nonetheless, this change is temporary and only applies to the current shell session. For a permanent solution, I might need to modify system files.

Potential Fixes for the future in webui:  
Further Optimize Resource Usage:  Ensure includes closing files, sockets, and other resources when they are no longer needed during RAG. 
Implement Caching or Pagination in RAG. 

These issues may also be handled by Haystack - as I've seen in one of the feature suggestions.
