### ISSUE TITLE
Unable to delete broken chat

### ISSUE THREAD

**Issue by Zambito1** [open-webui/open-webui#1139]
# Bug Report

## Description

**Bug Summary:**
I apologize that this will be pretty vague, but I have a chat that simply will hang the UI when I try to click on it. The only way I can navigate away from it is by refreshing the page. Hovering overy things in the interface will highlight them as if I can click them, but clicking does nothing. I get this stack trace in the JS console (selectable text below):

![image](https://github.com/open-webui/open-webui/assets/7004857/2cd097dd-b4f0-4797-b233-113d168c8270)

**Steps to Reproduce:**
It's hard for me to give the exact steps because I cannot see the chat history. From what I recall: I was playing with Modelfiles, and I accidentally created a chat that printed a ton of newlines. I'm not *certain* that this was that chat unfortunately, but given the `srollHeight` in the error, it seems to point in that direction to me.

**Expected Behavior:**
I should be able to select the chat and view the dialog. After selecting the chat, I should be able to navigate away from it.

**Actual Behavior:**
After selecting the chat I see a blank screen (no dialog):
![image](https://github.com/open-webui/open-webui/assets/7004857/0e890ab7-20fa-48ae-b0d8-edc53284f82b)

And clicking things that should navigate away (anything in the left column) has no effect.

## Environment

- **Operating System:** [GNU Guix]
- **Browser (if applicable):** The issue is replicatable in Ungoogled Chromium 112.0.5615.165 and GNU IceCat 115.8.0esr

## Reproduction Details

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [X] I have included the browser console logs.
- [X] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
```
caught TypeError: Cannot read properties of undefined (reading 'scrollHeight')
    at j (5.a2bb7993.js:5:1122)
    at 5.a2bb7993.js:12:3513
index.7b9b8c0f.js:114 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at $t.blockTokens (index.7b9b8c0f.js:114:221)
    at fn.blockquote (index.7b9b8c0f.js:103:691)
    at $t.blockTokens (index.7b9b8c0f.js:117:336)
    at fn.blockquote (index.7b9b8c0f.js:103:691)
    at $t.blockTokens (index.7b9b8c0f.js:117:336)
    at fn.blockquote (index.7b9b8c0f.js:103:691)
    at $t.blockTokens (index.7b9b8c0f.js:117:336)
    at fn.blockquote (index.7b9b8c0f.js:103:691)
    at $t.blockTokens (index.7b9b8c0f.js:117:336)
```

**Docker Container Logs:**
N/A, just GET the chat UUID.

**Screenshots (if applicable):**
See above

## Installation Method

docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main

## Additional Information

I don't have the exact Modelfile that I was using, but it shouldn't be hard to create one that will spam newlines. I was playing around with the TEMPLATE of text completion models (rather than instruct / chat models).

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Hi, I wasn't able to reproduce the issue but I edited some code which might resolve your issue to our dev branch. Let me know if that fixes the issue!

**Comment by Zambito1** [comment]
Thannks for taking a look. I tried it out on `dev` and I am able to see the text of the chat now, but it still stops me from navigating away.

This is the log I get now:

```
5.bb8deae7.js:5 {id: '', title: '[-] ##### #####\n', models: Array(1), options: {…}, messages: Array(2), …}
Navbar.602c3cc2.js:114 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at $t.blockTokens (Navbar.602c3cc2.js:114:221)
    at fn.blockquote (Navbar.602c3cc2.js:103:691)
    at $t.blockTokens (Navbar.602c3cc2.js:117:336)
    at fn.blockquote (Navbar.602c3cc2.js:103:691)
    at $t.blockTokens (Navbar.602c3cc2.js:117:336)
    at fn.blockquote (Navbar.602c3cc2.js:103:691)
    at $t.blockTokens (Navbar.602c3cc2.js:117:336)
    at fn.blockquote (Navbar.602c3cc2.js:103:691)
    at $t.blockTokens (Navbar.602c3cc2.js:117:336)
blockTokens @ Navbar.602c3cc2.js:114
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
blockquote @ Navbar.602c3cc2.js:103
blockTokens @ Navbar.602c3cc2.js:117
Promise.then (async)
it @ scheduler.161605a7.js:1
_t @ index.acd0f037.js:4
(anonymous) @ index.acd0f037.js:4
ye @ 5.bb8deae7.js:5
await in ye (async)
(anonymous) @ 5.bb8deae7.js:11
At.o.$$.update @ 5.bb8deae7.js:11
lt @ scheduler.161605a7.js:1
rt @ scheduler.161605a7.js:1
Promise.then (async)
it @ scheduler.161605a7.js:1
_t @ index.acd0f037.js:4
(anonymous) @ index.acd0f037.js:4
a.$$set @ app.94934f5d.js:1
$set @ index.acd0f037.js:4
ce @ start.c4d239eb.js:1
await in ce (async)
(anonymous) @ start.c4d239eb.js:1
```

If it helps, this is the content of the chat. It's not the one that I was thinking of before where it went off the screen with newlines.

![image](https://github.com/open-webui/open-webui/assets/7004857/d2a53acd-77aa-43b9-90d1-9b665521ea9a)

Unfortunately I have iterated on the Modelfile since then, so I am not able to get that to you for testing either.

**Comment by tjbck** [comment]
Hmm, I'm not sure what would fix it, I'll move this to discussion for now. Let us know if you find a way to reliably reproduce the issue!
