### ISSUE TITLE
LiteLLM 1.31.10 release breaks open-webui

### ISSUE THREAD

**Issue by jfernandrezj** [open-webui/open-webui#1168]
# Bug Report

## Description

**Bug Summary:**
open-webui  | Traceback (most recent call last):
open-webui  |   File "/usr/local/bin/uvicorn", line 8, in <module>
open-webui  |     sys.exit(main())
open-webui  |              ^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
open-webui  |     return self.main(*args, **kwargs)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
open-webui  |     rv = self.invoke(ctx)
open-webui  |          ^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
open-webui  |     return ctx.invoke(self.callback, **ctx.params)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
open-webui  |     return __callback(*args, **kwargs)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 409, in main
open-webui  |     run(
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 575, in run
open-webui  |     server.run()
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 62, in run
open-webui  |     return asyncio.run(self.serve(sockets=sockets))
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
open-webui  |     return runner.run(main)
open-webui  |            ^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
open-webui  |     return self._loop.run_until_complete(task)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
open-webui  |     config.load()
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 433, in load
open-webui  |     self.loaded_app = import_from_string(self.app)
open-webui  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 22, in import_from_string
open-webui  |     raise exc from None
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
open-webui  |     module = importlib.import_module(module_str)
open-webui  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
open-webui  |     return _bootstrap._gcd_import(name[level:], package, level)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
open-webui  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
open-webui  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
open-webui  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
open-webui  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
open-webui  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
open-webui  |   File "/app/backend/main.py", line 18, in <module>
open-webui  |     from litellm.proxy.proxy_server import ProxyConfig, initialize
open-webui  |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 150, in <module>
open-webui  |     import enterprise  # type: ignore
open-webui  |     ^^^^^^^^^^^^^^^^^

**Steps to Reproduce:**
Run the Docker Compose

**Expected Behavior:**
It should work

**Actual Behavior:**
Errors out

## Environment
Ubuntu 22.04

## Reproduction Details

**Confirmation:**

- [ ] I have read and followed all the instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
open-webui  | Traceback (most recent call last):
open-webui  |   File "/usr/local/bin/uvicorn", line 8, in <module>
open-webui  |     sys.exit(main())
open-webui  |              ^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
open-webui  |     return self.main(*args, **kwargs)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
open-webui  |     rv = self.invoke(ctx)
open-webui  |          ^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
open-webui  |     return ctx.invoke(self.callback, **ctx.params)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
open-webui  |     return __callback(*args, **kwargs)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 409, in main
open-webui  |     run(
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 575, in run
open-webui  |     server.run()
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 62, in run
open-webui  |     return asyncio.run(self.serve(sockets=sockets))
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
open-webui  |     return runner.run(main)
open-webui  |            ^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
open-webui  |     return self._loop.run_until_complete(task)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
open-webui  |     config.load()
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 433, in load
open-webui  |     self.loaded_app = import_from_string(self.app)
open-webui  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 22, in import_from_string
open-webui  |     raise exc from None
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
open-webui  |     module = importlib.import_module(module_str)
open-webui  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
open-webui  |     return _bootstrap._gcd_import(name[level:], package, level)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
open-webui  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
open-webui  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
open-webui  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
open-webui  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
open-webui  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
open-webui  |   File "/app/backend/main.py", line 18, in <module>
open-webui  |     from litellm.proxy.proxy_server import ProxyConfig, initialize
open-webui  |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 150, in <module>
open-webui  |     import enterprise  # type: ignore
open-webui  |     ^^^^^^^^^^^^^^^^^

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

Docker Compose

## Additional Information

https://github.com/BerriAI/litellm/releases/tag/v1.31.10
Using LiteLLM v1.30.2 works

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by justinh-rahb** [comment]
Should be easy to resolve by constraining the allowable versions to install in `requirements.txt`

**Comment by jfernandrezj** [comment]
Nevermind, resolved in latest release

**Comment by jfernandrezj** [comment]
Had a previous release where it was not constrained
