### ISSUE TITLE
The thing I wish you improved is... for it to work :')

### ISSUE THREAD

**Issue by roda37** [open-webui/open-webui#1404]
`No WEBUI_SECRET_KEY provided
Loading WEBUI_SECRET_KEY from .webui_secret_key
Traceback (most recent call last):
  File "/usr/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/usr/lib/python3.11/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/usr/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/usr/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/usr/lib/python3.11/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/w/stuff/AI/open-webui/backend/main.py", line 20, in <module>
    from apps.litellm.main import app as litellm_app, startup as litellm_app_startup
  File "/home/w/stuff/AI/open-webui/backend/apps/litellm/main.py", line 1, in <module>
    from litellm.proxy.proxy_server import ProxyConfig, initialize
  File "/home/w/.local/lib/python3.11/site-packages/litellm/__init__.py", line 4, in <module>
    from litellm.caching import Cache
  File "/home/w/.local/lib/python3.11/site-packages/litellm/caching.py", line 14, in <module>
    from openai._models import BaseModel as OpenAIObject
  File "/home/w/.local/lib/python3.11/site-packages/openai/__init__.py", line 8, in <module>
    from . import types
  File "/home/w/.local/lib/python3.11/site-packages/openai/types/__init__.py", line 5, in <module>
    from .image import Image as Image
  File "/home/w/.local/lib/python3.11/site-packages/openai/types/image.py", line 5, in <module>
    from .._models import BaseModel
  File "/home/w/.local/lib/python3.11/site-packages/openai/_models.py", line 21, in <module>
    import pydantic.generics
  File "/home/w/.local/lib/python3.11/site-packages/pydantic/generics.py", line 2, in <module>
    from ._migration import getattr_migration
  File "/home/w/.local/lib/python3.11/site-packages/pydantic/_migration.py", line 4, in <module>
    from .version import version_short
ImportError: cannot import name 'version_short' from 'pydantic.version' (/home/w/.local/lib/python3.11/site-packages/pydantic/version.cpython-311-x86_64-linux-gnu.so)`

It worked once, then it died under strange circumstances..

**Comment by justinh-rahb** [comment]
https://docs.openwebui.com/faq#q-i-updatedrestartedinstalled-some-new-software-and-now-my-webui-isnt-working-anymore

**Comment by roda37** [comment]
I am so stupid. Thanks.

for those that may be stuck just do this:

`
cd backend
python -m venv run
source run/activate
pip install -r requirements.txt
`
