### ISSUE TITLE
not found /manifest.json 404

### ISSUE THREAD

**Issue by algorithmlover2016** [open-webui/open-webui#1668]
# Bug Report

## Description
NotFound [Error]: Not found: /manifest.json
    at resolve (/disks/ssd2/litgao/codes/open-webui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:483:13)
    at resolve (/disks/ssd2/litgao/codes/open-webui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:277:5)
    at #options.hooks.handle (/disks/ssd2/litgao/codes/open-webui/node_modules/@sveltejs/kit/src/runtime/server/index.js:49:56)
    at Module.respond (/disks/ssd2/litgao/codes/open-webui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}
**Bug Summary:**
Not found: /manifest.json

**Steps to Reproduce:**
cd open-webui && npn install && npm run build && npm run dev

## Environment

- **Open WebUI Version:**  main 
- **Ollama (if applicable):** [e.g., 0.1.30, 0.1.32-rc1]

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

## Reproduction Details

**Confirmation:**

## Logs and Screenshots
![image](https://github.com/open-webui/open-webui/assets/17782711/b56c6656-04e9-4d59-b38f-e3b78f91931b)

**Comment by algorithmlover2016** [comment]
https://github.com/open-webui/open-webui/commit/83ad488e314dff5c0eceb700221c4374229b31e9

**Comment by algorithmlover2016** [comment]
I find that it need load static/manifest.json file, which means it will visit http://localhost:5173/manifest.json
It will not visit to backend's server, which is http://localhost:8080/manifest.json.

What should do to make dynamically load manifest.json successfully for src/app.html.
<link rel="manifest" href="%sveltekit.assets%/manifest.json" crossorigin="use-credentials" />

**Comment by justinh-rahb** [comment]
I'm not quite understanding what the problem is here, or what your PR is solving. More explanation may help.
