### ISSUE TITLE
enhancement: litellm opt-out support

### ISSUE THREAD

**Issue by imkebe** [open-webui/open-webui#1750]
# Bug Report

## Description

**Bug Summary:**
Frontend seems to fail because of the `/itellm/api/v1/models` timeout.

**Steps to Reproduce:**
Updated to v0.1.121

**Expected Behavior:**
There shouldn't be any hard LiteLLM deps.

**Actual Behavior:**
After login page the screen is empty. Pending llm models api fetch, while the service has never started.

## Environment

- **Open WebUI Version:** 
0.1.121

- **Ollama (if applicable):** 
0.1.30, 0.1.32

- **Browser (if applicable):** 
Brave 1.65.114 Chromium: 124.0.6367.60  , Firefox 125.0.2

## Reproduction Details

```INFO:apps.litellm.main:Executing command: ['litellm', '--port', '14365', '--host', '127.0.0.1', '--telemetry', 'False', '--config', '/app/backend/data/litellm/config.yaml']
ERROR:apps.litellm.main:Failed to start subprocess: [Errno 12] Cannot allocate memory
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-3' coro=<start_litellm_background() done, defined at /app/backend/apps/litellm/main.py:98> exception=OSError(12, 'Cannot allocate memory')>
Traceback (most recent call last):
  File "/app/backend/apps/litellm/main.py", line 113, in start_litellm_background
    await run_background_process(command)
  File "/app/backend/apps/litellm/main.py", line 74, in run_background_process
    process = await asyncio.create_subprocess_exec(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/subprocess.py", line 223, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 2820, in subprocess_exec
  File "uvloop/loop.pyx", line 2778, in __subprocess_run
  File "uvloop/handles/process.pyx", line 611, in uvloop.loop.UVProcessTransport.new
  File "uvloop/handles/process.pyx", line 112, in uvloop.loop.UVProcess._init
OSError: [Errno 12] Cannot allocate memory
```

**Comment by imkebe** [comment]
Why this is a enhancement and no bug relatedThat was working fine with 0.1.120.

**Comment by imkebe** [comment]
Also I noticed that the issue is in fact not having a timeout. When I block the URI of that endpoint in browser the Frontend is rendering. So in fact it waits forever trying to fetch the data and blocks the rendering of the Frontend.
