### ISSUE TITLE
Start up failure due to error after "No WEBUI_SECRET_KEY provided"

### ISSUE THREAD

**Issue by lewismacnow** [open-webui/open-webui#2080]
### Discussed in https://github.com/open-webui/open-webui/discussions/1775

<div type='discussions-op-text'>

<sup>Originally posted by **chopin1998** April 26, 2024</sup>
i use this command to launch

`docker run -it --network=host -v open-webui:/app/backend/data -e OLLAMA_BASE_URL=http://127.0.0.1:7880 --name open-webui --restart always ghcr.io/open-webui/open-webui:main`

it stucked:

`○ → docker run -it --network=host -v open-webui:/app/backend/data -e OLLAMA_BASE_URL=http://127.0.0.1:7880 --name open-webui --restart always ghcr.io/open-webui/open-webui:main
No WEBUI_SECRET_KEY provided
Generating WEBUI_SECRET_KEY
Loading WEBUI_SECRET_KEY from .webui_secret_key
`

don't know why?</div>

Trace:

```
No WEBUI_SECRET_KEY provided
Loading WEBUI_SECRET_KEY from .webui_secret_key
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/backend/main.py", line 20, in <module>
    from apps.ollama.main import app as ollama_app
  File "/app/backend/apps/ollama/main.py", line 31, in <module>
    from apps.web.models.users import Users
  File "/app/backend/apps/web/models/users.py", line 8, in <module>
    from apps.web.internal.db import DB
  File "/app/backend/apps/web/internal/db.py", line 3, in <module>
    from config import SRC_LOG_LEVELS, DATA_DIR
  File "/app/backend/config.py", line 4, in <module>
    import chromadb
  File "/usr/local/lib/python3.11/site-packages/chromadb/__init__.py", line 3, in <module>
    from chromadb.api.client import Client as ClientCreator
  File "/usr/local/lib/python3.11/site-packages/chromadb/api/__init__.py", line 7, in <module>
    from chromadb.api.models.Collection import Collection
  File "/usr/local/lib/python3.11/site-packages/chromadb/api/models/Collection.py", line 57, in <module>
    class Collection(BaseModel):
  File "/usr/local/lib/python3.11/site-packages/chromadb/api/models/Collection.py", line 74, in Collection
    ] = ef.DefaultEmbeddingFunction(),  # type: ignore
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chromadb/utils/embedding_functions.py", line 566, in DefaultEmbeddingFunction
    return ONNXMiniLM_L6_V2()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chromadb/utils/embedding_functions.py", line 409, in __init__
    self.tqdm = importlib.import_module("tqdm").tqdm
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tqdm/__init__.py", line 2, in <module>
    from ._tqdm_pandas import tqdm_pandas
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1069, in get_code
  File "<frozen importlib._bootstrap_external>", line 729, in _compile_bytecode
ValueError: bad marshal data (unknown type code)
```

**Comment by justinh-rahb** [comment]
"errors" related to `WEBUI_SECRET_KEY` are red herrings.. inconsequential to the running of the app, if you read that entirely you'll see that it creates one if none is provided (this is the expected behaviour).

**Comment by lewismacnow** [comment]
> "errors" related to `WEBUI_SECRET_KEY` missing are red herrings.. inconsequential to the running of the app, it will create one if none is provided (this is the expected behaviour).

The app is in a restart loop, this is the only contents of the log. Something is happening this:
![image](https://github.com/open-webui/open-webui/assets/93997957/8a70e89d-861e-4770-afe9-f0a793119047)
