### ISSUE TITLE
Problem updating reranking model: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by chrisoutwright** [open-webui/open-webui#2353]
# Bug Report

## Description

**Bug Summary:**
When attempting to update the reranking model from `` to `llm-blender/PairRM` in Open WebUI, an `AttributeError` occurs. This error suggests a possible issue with model metadata not being properly initialized or handled, specifically the `NoneType` object not having a `get` attribute.

**Steps to Reproduce:**
1. Launch Open WebUI.
2. Navigate to the reranking model update section via the UI.
3. Trigger a model update by selecting the option to update from `llm-blender/PairRM` to `llm-blender/PairRM`.
4. Observe the error in the system logs and the failure notification in the UI.

**Expected Behavior:**
The model update should complete successfully without errors, allowing the new reranking model to be utilized for enhanced performance.

**Actual Behavior:**
The update fails, resulting in a `500 Internal Server Error`. The logs indicate an `AttributeError` due to trying to access a `get` method on a `NoneType` object.

## Environment

- **Open WebUI Version:** v0.1.124 (latest)
- **Ollama Version:** 0.1.36
- **Operating System:** Windows 11 with WSL2 and Docker for Desktop
- **Browser:** Chrome

## Logs Details

```

INFO:apps.rag.main:Updating reranking model: ibm/re2g-reranker-nq to llm-blender/PairRM
Fetching 11 files: 100%|
ERROR:apps.rag.main:Problem updating reranking model: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Users\Chris\OpenWebUI\open-webui\backend\apps\rag\main.py", line 298, in update_reranking_config
    update_reranking_model(app.state.RAG_RERANKING_MODEL, True)
  File "C:\Users\Chris\OpenWebUI\open-webui\backend\apps\rag\main.py", line 151, in update_reranking_model
    app.state.sentence_transformer_rf = sentence_transformers.CrossEncoder(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py", line 81, in __init__
    self.model = AutoModelForSequenceClassification.from_pretrained(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\models\auto\auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\modeling_utils.py", line 3313, in from_pretrained
    if metadata.get("format") == "pt":
       ^^^^^^^^^^^^
```

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [] I have included the browser console logs.
- [x] I have included the Docker container logs.

**Comment by chrisoutwright** [comment]
Strangely enough this works when I do not enter any -e parameters in a fresh docker for open-webui:latest.
There I can enter llm-blender/PairRM as reranking model without issue.
