### ISSUE TITLE
bug: Open WebUI fails to start after update

### ISSUE THREAD

**Issue by bannert1337** [open-webui/open-webui#2758]
# Bug Report

## Description

**Bug Summary:**
After I updated the Docker Image, I am getting this error when trying to access it:
```
open-webui  | Loading WEBUI_SECRET_KEY from .webui_secret_key
open-webui  | CUDA is enabled, appending LD_LIBRARY_PATH to include torch/cudnn & cublas libraries.
open-webui  | Cannot determine model snapshot path: Cannot find an appropriate cached snapshot folder for the specified revision on the local disk and outgoing traffic has been disabled. To enable repo look-ups and downloads online, pass 'local_files_only=False' as input.
open-webui  | Traceback (most recent call last):
open-webui  |   File "/app/backend/apps/rag/utils.py", line 407, in get_model_path
open-webui  |     model_repo_path = snapshot_download(**snapshot_kwargs)
open-webui  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
open-webui  |     return fn(*args, **kwargs)
open-webui  |            ^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 220, in snapshot_download
open-webui  |     raise LocalEntryNotFoundError(
open-webui  | huggingface_hub.utils._errors.LocalEntryNotFoundError: Cannot find an appropriate cached snapshot folder for the specified revision on the local disk and outgoing traffic has been disabled. To enable repo look-ups and downloads online, pass 'local_files_only=False' as input.
open-webui  | /usr/local/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
open-webui  |   warnings.warn(
open-webui  | Traceback (most recent call last):
open-webui  |   File "/usr/local/bin/uvicorn", line 8, in <module>
open-webui  |     sys.exit(main())
open-webui  | /app
open-webui  |              ^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
open-webui  |     return self.main(*args, **kwargs)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
open-webui  |     rv = self.invoke(ctx)
open-webui  |          ^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
open-webui  |     return ctx.invoke(self.callback, **ctx.params)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
open-webui  |     return __callback(*args, **kwargs)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 410, in main
open-webui  |     run(
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 578, in run
open-webui  |     server.run()
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
open-webui  |     return asyncio.run(self.serve(sockets=sockets))
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
open-webui  |     return runner.run(main)
open-webui  |            ^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
open-webui  |     return self._loop.run_until_complete(task)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
open-webui  |     config.load()
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
open-webui  |     self.loaded_app = import_from_string(self.app)
open-webui  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
open-webui  |     module = importlib.import_module(module_str)
open-webui  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
open-webui  |     return _bootstrap._gcd_import(name[level:], package, level)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
open-webui  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
open-webui  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
open-webui  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
open-webui  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
open-webui  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
open-webui  |   File "/app/backend/main.py", line 28, in <module>
open-webui  |     from apps.rag.main import app as rag_app
open-webui  |   File "/app/backend/apps/rag/main.py", line 203, in <module>
open-webui  |     update_reranking_model(
open-webui  |   File "/app/backend/apps/rag/main.py", line 189, in update_reranking_model
open-webui  |     app.state.sentence_transformer_rf = sentence_transformers.CrossEncoder(
open-webui  |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 81, in __init__
open-webui  |     self.model = AutoModelForSequenceClassification.from_pretrained(
open-webui  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
open-webui  |     return model_class.from_pretrained(
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3534, in from_pretrained
open-webui  |     if metadata.get("format") == "pt":
open-webui  |        ^^^^^^^^^^^^
open-webui  | AttributeError: 'NoneType' object has no attribute 'get'
open-webui exited with code 0
```

**Steps to Reproduce:**
1. Update Open WebUI Docker Container to the latest Image build.
2. Access the WebUI from browser.
3. Check console.

**Expected Behavior:**
Start correctly.

**Actual Behavior:**
[Describe what actually happened.]

## Environment

- **Open WebUI Version:** `0.2.2`

**Comment by bannert1337** [comment]
I set a Reranking model yesterday. The model I set was `llm-blender/PairRM`.

**Comment by bannert1337** [comment]
I used the `RESET_CONFIG_ON_START` env set to true and now the WebUI is accessible again, but with all settings reset (as expected).
