### ISSUE TITLE
Internal Server Error with fresh setup (docker)

### ISSUE THREAD

**Issue by MarvinJWendt** [open-webui/open-webui#3166]
# Bug Report

## Description

**Bug Summary:**
After setting up open-webui with docker compose, it crashes on start.

**Steps to Reproduce:**
Docker compose:

```yaml
name: open-webui

services:
  open-webui:
    restart: always
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 3000:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./data:/app/backend/data
    container_name: open-webui
```

- docker compose up
- error

**Expected Behavior:**
No error.

**Actual Behavior:**
Internal Server Error

## Environment

- **Open WebUI Version:** docker image (main)
- **Ollama (if applicable):** 0.1.44

- **Operating System:** macOS latest via Docker
- **Browser (if applicable):** Chrome

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Docker Container Logs:**

```
open-webui  | Loading WEBUI_SECRET_KEY from file, not provided as an environment variable.
open-webui  | Generating WEBUI_SECRET_KEY
open-webui  | Loading WEBUI_SECRET_KEY from .webui_secret_key
open-webui  | INFO:     Started server process [1]
open-webui  | INFO:     Waiting for application startup.
open-webui  | INFO:     Application startup complete.
open-webui  | INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
open-webui  | /app
open-webui  | 
open-webui  |   ___                    __        __   _     _   _ ___ 
open-webui  |  / _ \ _ __   ___ _ __   \ \      / /__| |__ | | | |_ _|
open-webui  | | | | | '_ \ / _ \ '_ \   \ \ /\ / / _ \ '_ \| | | || | 
open-webui  | | |_| | |_) |  __/ | | |   \ V  V /  __/ |_) | |_| || | 
open-webui  |  \___/| .__/ \___|_| |_|    \_/\_/ \___|_.__/ \___/|___|
open-webui  |       |_|                                               
open-webui  | 
open-webui  |       
open-webui  | v0.3.4 - building the best open-source AI user interface.
open-webui  | 
open-webui  | https://github.com/open-webui/open-webui
open-webui  | 
open-webui  | INFO:apps.openai.main:get_all_models()
open-webui  | INFO:apps.ollama.main:get_all_models()
open-webui  | INFO:     127.0.0.1:51398 - "GET /health HTTP/1.1" 500 Internal Server Error
open-webui  | ERROR:    Exception in ASGI application
open-webui  |   + Exception Group Traceback (most recent call last):
open-webui  |   |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 87, in collapse_excgroups
open-webui  |   |     yield
open-webui  |   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 190, in __call__
open-webui  |   |     async with anyio.create_task_group() as task_group:
open-webui  |   |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
open-webui  |   |     raise BaseExceptionGroup(
open-webui  |   | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
open-webui  |   +-+---------------- 1 ----------------
open-webui  |     | Traceback (most recent call last):
open-webui  |     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
open-webui  |     |     result = await app(  # type: ignore[func-returns-value]
open-webui  |     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
open-webui  |     |     return await self.app(scope, receive, send)
open-webui  |     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |     |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
open-webui  |     |     await super().__call__(scope, receive, send)
open-webui  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
open-webui  |     |     await self.middleware_stack(scope, receive, send)
open-webui  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
open-webui  |     |     raise exc
open-webui  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
open-webui  |     |     await self.app(scope, receive, _send)
open-webui  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
open-webui  |     |     with collapse_excgroups():
open-webui  |     |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
open-webui  |     |     self.gen.throw(typ, value, traceback)
open-webui  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
open-webui  |     |     raise exc
open-webui  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
open-webui  |     |     response = await self.dispatch_func(request, call_next)
open-webui  |     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |     |   File "/app/backend/main.py", line 576, in update_embedding_function
open-webui  |     |     response = await call_next(request)
open-webui  |     |                ^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
open-webui  |     |     raise app_exc
open-webui  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
open-webui  |     |     await self.app(scope, receive_or_disconnect, send_no_error)
open-webui  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
open-webui  |     |     with collapse_excgroups():
open-webui  |     |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
open-webui  |     |     self.gen.throw(typ, value, traceback)
open-webui  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
open-webui  |     |     raise exc
open-webui  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
open-webui  |     |     response = await self.dispatch_func(request, call_next)
open-webui  |     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |     |   File "/app/backend/main.py", line 562, in check_url
open-webui  |     |     await get_all_models()
open-webui  |     |   File "/app/backend/main.py", line 607, in get_all_models
open-webui  |     |     ollama_models = await get_ollama_models()
open-webui  |     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |     |   File "/app/backend/apps/ollama/main.py", line 222, in get_all_models
open-webui  |     |     app.state.MODELS = {model["model"]: model for model in models["models"]}
open-webui  |     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |     |   File "/app/backend/apps/ollama/main.py", line 222, in <dictcomp>
open-webui  |     |     app.state.MODELS = {model["model"]: model for model in models["models"]}
open-webui  |     |                         ~~~~~^^^^^^^^^
open-webui  |     | KeyError: 'model'
open-webui  |     +------------------------------------
open-webui  | 
open-webui  | During handling of the above exception, another exception occurred:
open-webui  | 
open-webui  | Traceback (most recent call last):
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
open-webui  |     result = await app(  # type: ignore[func-returns-value]
open-webui  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
open-webui  |     return await self.app(scope, receive, send)
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
open-webui  |     await super().__call__(scope, receive, send)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
open-webui  |     await self.middleware_stack(scope, receive, send)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
open-webui  |     raise exc
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
open-webui  |     await self.app(scope, receive, _send)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
open-webui  |     with collapse_excgroups():
open-webui  |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
open-webui  |     self.gen.throw(typ, value, traceback)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
open-webui  |     raise exc
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
open-webui  |     response = await self.dispatch_func(request, call_next)
open-webui  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/app/backend/main.py", line 576, in update_embedding_function
open-webui  |     response = await call_next(request)
open-webui  |                ^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
open-webui  |     raise app_exc
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
open-webui  |     await self.app(scope, receive_or_disconnect, send_no_error)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
open-webui  |     with collapse_excgroups():
open-webui  |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
open-webui  |     self.gen.throw(typ, value, traceback)
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
open-webui  |     raise exc
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
open-webui  |     response = await self.dispatch_func(request, call_next)
open-webui  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/app/backend/main.py", line 562, in check_url
open-webui  |     await get_all_models()
open-webui  |   File "/app/backend/main.py", line 607, in get_all_models
open-webui  |     ollama_models = await get_ollama_models()
open-webui  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/app/backend/apps/ollama/main.py", line 222, in get_all_models
open-webui  |     app.state.MODELS = {model["model"]: model for model in models["models"]}
open-webui  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui  |   File "/app/backend/apps/ollama/main.py", line 222, in <dictcomp>
open-webui  |     app.state.MODELS = {model["model"]: model for model in models["models"]}
open-webui  |                         ~~~~~^^^^^^^^^
open-webui  | KeyError: 'model'
```

## Installation Method

Docker via docker compose, as mentioned above.

**Comment by MarvinJWendt** [comment]
After reinstalling ollama it works now, but I think it's weird that a broken ollama installation will completely break the webui, as it's not necessarily used with ollama. Maybe this should still be adressed? Otherwise, feel free to close it :)
