### ISSUE TITLE
OIDC authorization fails to log in

### ISSUE THREAD

**Issue by bigun27** [open-webui/open-webui#3551]
# Bug Report

## Description

**Bug Summary:**
I have configured OAuth according to the docs using Authentik. The authorization is successful on the Authentik side, redirects to the Open WebUI callback, and it fails.

The browser displays: 
`{"detail":"The email or password provided is incorrect. Please check for typos and try logging in again."}`

**Expected Behavior:**
Successful login to Open WebUI

**Actual Behavior:**
No login to Open WebUI

## Environment

- **Open WebUI Version:** 0.3.6 and 0.3.7

- **Operating System:** Linux
- **Browser (if applicable):** Firefox 127 and Chrome 126

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Docker Container Logs:**
```
open-webui  | INFO:     192.168.1.15:0 - "GET /oauth/oidc/login HTTP/1.1" 302 Found
open-webui  | INFO:httpx:HTTP Request: POST https://authentik.***/application/o/token/ "HTTP/1.1 200 OK"
open-webui  | INFO:httpx:HTTP Request: GET https://authentik.***/application/o/open-webui/jwks/ "HTTP/1.1 200 OK"
open-webui  | INFO:httpx:HTTP Request: GET https://authentik.***/application/o/open-webui/jwks/ "HTTP/1.1 200 OK"
open-webui  | WARNING:main:OAuth callback error: Invalid key set format
open-webui  | INFO:     192.168.1.15:0 - "GET /oauth/oidc/callback?code=72936687cb604dac9c24396dcfe5jssy&state=BK98k4OjDea2MQRaus3gvj8R4Ghpvm HTTP/1.1" 400 Bad Request
```

## Installation Method

Docker compose on a Debian host
OAuth authorized by Authentik 2024.6.0 (latest)

## Additional Information

Docker environment variables:
```
    environment:
      - 'ENABLE_OAUTH_SIGNUP=true'
      - 'OAUTH_CLIENT_ID==*******''
      - 'OAUTH_CLIENT_SECRET=*******'
      - 'OPENID_PROVIDER_URL=https://authentik.***/application/o/open-webui/.well-known/openid-configuration'
```

**Comment by chriscowley** [comment]
I'd like to add that I am having the same behaviour, using the same settings in my environment. The only difference is that I have tried with 2 users in Authentik. One should map onto an existing user in Open Webui (using OAUTH_MERGE_ACCOUNTS_BY_EMAIL) another which should create a new user.

I'll also add the traceback in my logs:

```
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 87, in collapse_excgroups
  |     yield
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 190, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    |     raise exc
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    |     await self.app(scope, receive, send_wrapper)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    |     with collapse_excgroups():
    |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    |     raise exc
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/app/backend/main.py", line 807, in update_embedding_function
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 166, in call_next
    |     raise RuntimeError("No response returned.")
    | RuntimeError: No response returned.
    +------------------------------------
```

**Comment by TShapinsky** [comment]
I am also experiencing this behavior with Authentik OIDC. But given that the OAuth feature is both experimental and only 4 days from release I'm hopeful it'll be working soon.

**Comment by ericxliu1990** [comment]
+1 . I saw the same issues.

**Comment by TShapinsky** [comment]
I was able to get it working. 
1. By turning off `OAUTH_MERGE_ACCOUNTS_BY_EMAIL` and changing the email of the OAuth user to one not present on the local open-webui instance it got through to the pending screen.

I wonder if `OAUTH_MERGE_ACCOUNTS_BY_EMAIL` is broken or if it's due to bringing in an old database.

Either way, I nuked the configuration for open-webui and logged in with my OAuth user, and it appears to be working.

**Comment by ericxliu1990** [comment]
+1 TShapinsky's comments. 

I was able to fix the issues by nuking the config and start a new instance with OAUTH_MERGE_ACCOUNTS_BY_EMAIL disabled. I was using 0.3.7.

**Comment by bigun27** [comment]
I deleted my Authentik application and provider, then created new ones with the exact same settings as before. After loading in the values of the new provider, everything works. Even merge by email.

I have no explanation as to why it works now.

**Comment by keesfluitman** [comment]
> +1 TShapinsky's comments.
> 
> I was able to fix the issues by nuking the config and start a new instance with OAUTH_MERGE_ACCOUNTS_BY_EMAIL disabled. I was using 0.3.7.

What do you mean nuke the config? A config file or.simply redeploy the docker container?

**Comment by TShapinsky** [comment]
> > +1 TShapinsky's comments.
> > I was able to fix the issues by nuking the config and start a new instance with OAUTH_MERGE_ACCOUNTS_BY_EMAIL disabled. I was using 0.3.7.
> 
> What do you mean nuke the config? A config file or.simply redeploy the docker container?

I just got rid of all persistent data. I'm running on k8s so the process is different, but if you're in docker just deleting the volume would have the same effect. It definitely has downsides of losing all your data, but I didn't have much of value in it anyways.

**Comment by keesfluitman** [comment]
> > > +1 TShapinsky's comments.
> > > I was able to fix the issues by nuking the config and start a new instance with OAUTH_MERGE_ACCOUNTS_BY_EMAIL disabled. I was using 0.3.7.
> > 
> > 
> > What do you mean nuke the config? A config file or.simply redeploy the docker container?
> 
> I just got rid of all persistent data. I'm running on k8s so the process is different, but if you're in docker just deleting the volume would have the same effect. It definitely has downsides of losing all your data, but I didn't have much of value in it anyways.

Perfect ill try. Im just setting up, havent had any constructive conversations with it either ;).

**Comment by zylhuang** [comment]
I'm experiencing the same issue here. OIDC just doesn't work suddenly without any config change. This happened to all my OIDC instances now, including **Overleaf Pro** and **Outline**. I also started a newly installed Authentik docker to reproduce, which ended up with the same problem.

During an OIDC authentication, when browser redirects to application URL (Outline for example) from authentik page, it returns 502 bad gateway. Here is the outline logs, since no error found in the authentik logs(I replaced my real IP with many X): 

> outline-outline-1   | {"error":"connect ETIMEDOUT XXX.XXX.XXX.XX:443","level":"error","message":"Error during authentication","stack":"Error: connect ETIMEDOUT XXX.XXX.XXX.XX:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)"}

![image](https://github.com/user-attachments/assets/2d062ae7-6bfb-4dbb-8514-71566b651965)

**Comment by justinh-rahb** [comment]
@zylhuang your issue seems to be with your authentication server, not the services using it.

**Comment by Schumacher-Bastian** [comment]
I am experiencing the same issue using Microsoft OAuth. Despite configuring everything according to the documentation, I receive the same error regardless of whether `OAUTH_MERGE_ACCOUNTS_BY_EMAIL` is enabled and whether a user with the same email address already exists. The system consistently fails to log in and does not create a new user. This seems to indicate a broader problem with the OAuth implementation, possibly related to the JWKS key set handling. Any insights or solutions would be greatly appreciated.

**Comment by DanielWeeber** [comment]
> I am experiencing the same issue using Microsoft OAuth. Despite configuring everything according to the documentation, I receive the same error regardless of whether `OAUTH_MERGE_ACCOUNTS_BY_EMAIL` is enabled and whether a user with the same email address already exists. The system consistently fails to log in and does not create a new user. This seems to indicate a broader problem with the OAuth implementation, possibly related to the JWKS key set handling. Any insights or solutions would be greatly appreciated.

same here.
