### ISSUE TITLE
Back-end error when uploading the same document twice in two conversations

### ISSUE THREAD

**Issue by leobenkel** [open-webui/open-webui#3680]
# Bug Report

## Description

**Bug Summary:**

Error are showing up in the log when the same document is uploaded twice.

**Steps to Reproduce:**

 1. open a conversation, drop a document, as a question
 2. open a different conversation, drop the same document, look at back end log.

**Expected Behavior:**

Would identify that this document as already been vectorized and stored and reuse the cache. Maybe have a hash of (the doc content + modified date + name) as collection name ? 

**Actual Behavior:**

It seems to be working, but i see errors in the back-end log.

## Environment

all latest
firefox

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Docker Container Logs:**
```
ERROR:apps.rag.main:Collection 0509bce7e32b04c3892a9f838867309b3000d9f323673549489899b60021bfd already exists
Traceback (most recent call last):
  File "/app/./src/apps/rag/main.py", line 956, in store_docs_in_vector_db
    collection = CHROMA_CLIENT.create_collection(name=collection_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/chromadb/api/client.py", line 112, in create_collection
    return self._server.create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/chromadb/api/segment.py", line 171, in create_collection
    coll, created = self._sysdb.create_collection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/chromadb/db/mixins/sysdb.py", line 220, in create_collection
    raise UniqueConstraintError(f"Collection {name} already exists")
```

**Comment by tjbck** [comment]
This is just for logging purposes!

**Comment by leobenkel** [comment]
ok, maybe not printed the stack trace would be nicer?

**Comment by tjbck** [comment]
Feel free to make a PR!

**Comment by leobenkel** [comment]
@tjbck done
