### ISSUE TITLE
WEBUI_AUTH=False doesn't work with fresh docker install v0.3.10

### ISSUE THREAD

**Issue by justicecurcian** [open-webui/open-webui#4070]
# Bug Report

## Description

**Bug Summary:**
With `WEBUI_AUTH=False` when I try to generate text I get an error:

```
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
openwebui-openwebui-1  |     response = await self.dispatch_func(request, call_next)
openwebui-openwebui-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |   File "/app/backend/main.py", line 847, in dispatch
openwebui-openwebui-1  |     get_http_authorization_cred(request.headers.get("Authorization")),
openwebui-openwebui-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |   File "/app/backend/utils/utils.py", line 75, in get_http_authorization_cred
openwebui-openwebui-1  |     raise ValueError(ERROR_MESSAGES.INVALID_TOKEN)
openwebui-openwebui-1  | ValueError: Your session has expired or the token is invalid. Please sign in again.
```

**Steps to Reproduce:**
1. Create fresh docker install with `WEBUI_AUTH=False`
2. Try to generate text with ollama

**Expected Behavior:**
Text generates

**Actual Behavior:**
Auth error

## Environment

- **Open WebUI Version:** v0.3.10
- **Ollama (if applicable):** 0.2.8
- **Operating System:** Ubunti server
- **Browser (if applicable):** Chrome 126.0

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Docker Container Logs:**
```
openwebui-openwebui-1  | INFO:     192.168.8.1:0 - "POST /ollama/api/chat HTTP/1.1" 500 Internal Server Error
openwebui-openwebui-1  | ERROR:    Exception in ASGI application
openwebui-openwebui-1  |   + Exception Group Traceback (most recent call last):
openwebui-openwebui-1  |   |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 87, in collapse_excgroups
openwebui-openwebui-1  |   |     yield
openwebui-openwebui-1  |   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 190, in __call__
openwebui-openwebui-1  |   |     async with anyio.create_task_group() as task_group:
openwebui-openwebui-1  |   |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
openwebui-openwebui-1  |   |     raise BaseExceptionGroup(
openwebui-openwebui-1  |   | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
openwebui-openwebui-1  |   +-+---------------- 1 ----------------
openwebui-openwebui-1  |     | Traceback (most recent call last):
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
openwebui-openwebui-1  |     |     result = await app(  # type: ignore[func-returns-value]
openwebui-openwebui-1  |     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
openwebui-openwebui-1  |     |     return await self.app(scope, receive, send)
openwebui-openwebui-1  |     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
openwebui-openwebui-1  |     |     await super().__call__(scope, receive, send)
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
openwebui-openwebui-1  |     |     await self.middleware_stack(scope, receive, send)
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
openwebui-openwebui-1  |     |     raise exc
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
openwebui-openwebui-1  |     |     await self.app(scope, receive, _send)
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
openwebui-openwebui-1  |     |     with collapse_excgroups():
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
openwebui-openwebui-1  |     |     self.gen.throw(typ, value, traceback)
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
openwebui-openwebui-1  |     |     raise exc
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
openwebui-openwebui-1  |     |     response = await self.dispatch_func(request, call_next)
openwebui-openwebui-1  |     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |     |   File "/app/backend/main.py", line 915, in update_embedding_function
openwebui-openwebui-1  |     |     response = await call_next(request)
openwebui-openwebui-1  |     |                ^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
openwebui-openwebui-1  |     |     raise app_exc
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
openwebui-openwebui-1  |     |     await self.app(scope, receive_or_disconnect, send_no_error)
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
openwebui-openwebui-1  |     |     with collapse_excgroups():
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
openwebui-openwebui-1  |     |     self.gen.throw(typ, value, traceback)
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
openwebui-openwebui-1  |     |     raise exc
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
openwebui-openwebui-1  |     |     response = await self.dispatch_func(request, call_next)
openwebui-openwebui-1  |     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |     |   File "/app/backend/main.py", line 906, in check_url
openwebui-openwebui-1  |     |     response = await call_next(request)
openwebui-openwebui-1  |     |                ^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
openwebui-openwebui-1  |     |     raise app_exc
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
openwebui-openwebui-1  |     |     await self.app(scope, receive_or_disconnect, send_no_error)
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
openwebui-openwebui-1  |     |     with collapse_excgroups():
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
openwebui-openwebui-1  |     |     self.gen.throw(typ, value, traceback)
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
openwebui-openwebui-1  |     |     raise exc
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
openwebui-openwebui-1  |     |     response = await self.dispatch_func(request, call_next)
openwebui-openwebui-1  |     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |     |   File "/app/backend/main.py", line 892, in commit_session_after_request
openwebui-openwebui-1  |     |     response = await call_next(request)
openwebui-openwebui-1  |     |                ^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
openwebui-openwebui-1  |     |     raise app_exc
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
openwebui-openwebui-1  |     |     await self.app(scope, receive_or_disconnect, send_no_error)
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
openwebui-openwebui-1  |     |     await self.simple_response(scope, receive, send, request_headers=headers)
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 148, in simple_response
openwebui-openwebui-1  |     |     await self.app(scope, receive, send)
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
openwebui-openwebui-1  |     |     with collapse_excgroups():
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
openwebui-openwebui-1  |     |     self.gen.throw(typ, value, traceback)
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
openwebui-openwebui-1  |     |     raise exc
openwebui-openwebui-1  |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
openwebui-openwebui-1  |     |     response = await self.dispatch_func(request, call_next)
openwebui-openwebui-1  |     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |     |   File "/app/backend/main.py", line 847, in dispatch
openwebui-openwebui-1  |     |     get_http_authorization_cred(request.headers.get("Authorization")),
openwebui-openwebui-1  |     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |     |   File "/app/backend/utils/utils.py", line 75, in get_http_authorization_cred
openwebui-openwebui-1  |     |     raise ValueError(ERROR_MESSAGES.INVALID_TOKEN)
openwebui-openwebui-1  |     | ValueError: Your session has expired or the token is invalid. Please sign in again.
openwebui-openwebui-1  |     +------------------------------------
openwebui-openwebui-1  | 
openwebui-openwebui-1  | During handling of the above exception, another exception occurred:
openwebui-openwebui-1  | 
openwebui-openwebui-1  | Traceback (most recent call last):
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
openwebui-openwebui-1  |     result = await app(  # type: ignore[func-returns-value]
openwebui-openwebui-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
openwebui-openwebui-1  |     return await self.app(scope, receive, send)
openwebui-openwebui-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
openwebui-openwebui-1  |     await super().__call__(scope, receive, send)
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
openwebui-openwebui-1  |     await self.middleware_stack(scope, receive, send)
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
openwebui-openwebui-1  |     raise exc
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
openwebui-openwebui-1  |     await self.app(scope, receive, _send)
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
openwebui-openwebui-1  |     with collapse_excgroups():
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
openwebui-openwebui-1  |     self.gen.throw(typ, value, traceback)
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
openwebui-openwebui-1  |     raise exc
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
openwebui-openwebui-1  |     response = await self.dispatch_func(request, call_next)
openwebui-openwebui-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |   File "/app/backend/main.py", line 915, in update_embedding_function
openwebui-openwebui-1  |     response = await call_next(request)
openwebui-openwebui-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
openwebui-openwebui-1  |     raise app_exc
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
openwebui-openwebui-1  |     await self.app(scope, receive_or_disconnect, send_no_error)
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
openwebui-openwebui-1  |     with collapse_excgroups():
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
openwebui-openwebui-1  |     self.gen.throw(typ, value, traceback)
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
openwebui-openwebui-1  |     raise exc
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
openwebui-openwebui-1  |     response = await self.dispatch_func(request, call_next)
openwebui-openwebui-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |   File "/app/backend/main.py", line 906, in check_url
openwebui-openwebui-1  |     response = await call_next(request)
openwebui-openwebui-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
openwebui-openwebui-1  |     raise app_exc
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
openwebui-openwebui-1  |     await self.app(scope, receive_or_disconnect, send_no_error)
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
openwebui-openwebui-1  |     with collapse_excgroups():
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
openwebui-openwebui-1  |     self.gen.throw(typ, value, traceback)
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
openwebui-openwebui-1  |     raise exc
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
openwebui-openwebui-1  |     response = await self.dispatch_func(request, call_next)
openwebui-openwebui-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |   File "/app/backend/main.py", line 892, in commit_session_after_request
openwebui-openwebui-1  |     response = await call_next(request)
openwebui-openwebui-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
openwebui-openwebui-1  |     raise app_exc
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
openwebui-openwebui-1  |     await self.app(scope, receive_or_disconnect, send_no_error)
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
openwebui-openwebui-1  |     await self.simple_response(scope, receive, send, request_headers=headers)
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 148, in simple_response
openwebui-openwebui-1  |     await self.app(scope, receive, send)
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
openwebui-openwebui-1  |     with collapse_excgroups():
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
openwebui-openwebui-1  |     self.gen.throw(typ, value, traceback)
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
openwebui-openwebui-1  |     raise exc
openwebui-openwebui-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
openwebui-openwebui-1  |     response = await self.dispatch_func(request, call_next)
openwebui-openwebui-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |   File "/app/backend/main.py", line 847, in dispatch
openwebui-openwebui-1  |     get_http_authorization_cred(request.headers.get("Authorization")),
openwebui-openwebui-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openwebui-openwebui-1  |   File "/app/backend/utils/utils.py", line 75, in get_http_authorization_cred
openwebui-openwebui-1  |     raise ValueError(ERROR_MESSAGES.INVALID_TOKEN)
openwebui-openwebui-1  | ValueError: Your session has expired or the token is invalid. Please sign in again.
```

## Installation Method
Docker install via Dockge (basically custom docker compose based on docker command from quickstart)

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by justicecurcian** [comment]
Looks like it's a problem on my end, `WEBUI_AUTH=True` doesn't work either. I use nginx to proxy my requests and I installed openwebui on a separate domain. It doesn't work when I access it via domain name, but it works when I access it via ip:port.
