### ISSUE TITLE
My instance stuck after testing pipe.

### ISSUE THREAD

**Issue by Tavernari** [open-webui/open-webui#5269]
# Bug Report

## Installation Method

I installed a pipe, so I tried to modify the file through the OpenWebUI, and then tried to delete it but it stuck to my webui system.

## Environment

- **Open WebUI Version:** v0.3.11
- **Ollama (if applicable):** N/A

- **Operating System:** Raspberry PI 5 8Gb
- **Browser (if applicable):** I was using Safari Version 18.0 (20619.1.15.11.1)

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

I would expect to use the pipe, but it was configured to use Ollama, so I changed to use OpenAI, after that everything exploded and blocked all systems from working.

## Actual Behavior:

Blocked all my chat and things stopped working.

## Description

**Bug Summary:**
I was testing pipes and after it it brokes.

## Reproduction Details

**Steps to Reproduce:**
I am not clear about reproduce:

I installed the pipe from the marketplace.
I tried to run the pipe but it was configured to Ollama
I changed it directly on the open web UI interface.
Tried to run again and it gave me an error
I tried to fix it, so after any success, I removed it.
So I reboot my raspberry PI and never back to work.

## Logs and Screenshots

**Browser Console Logs:**
N/A

**Docker Container Logs:**
```
/app

  ___                    __        __   _     _   _ ___ 
 / _ \ _ __   ___ _ __   \ \      / /__| |__ | | | |_ _|
| | | | '_ \ / _ \ '_ \   \ \ /\ / / _ \ '_ \| | | || | 
| |_| | |_) |  __/ | | |   \ V  V /  __/ |_) | |_| || | 
 \___/| .__/ \___|_| |_|    \_/\_/ \___|_.__/ \___/|___|
      |_|                                               

      
v0.3.11 - building the best open-source AI user interface.

https://github.com/open-webui/open-webui

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
Error: The file /app/backend/data/functions/langchain_pipe.py does not exist.
Error loading module: langchain_pipe
INFO:     2a01:11:8210:23a0:d994:d637:c9ff:3ece:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=P7H61Z2 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 87, in collapse_excgroups
  |     yield
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 190, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    |     raise exc
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    |     with collapse_excgroups():
    |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    |     raise exc
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/app/backend/main.py", line 902, in update_embedding_function
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    |     raise app_exc
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    |     with collapse_excgroups():
    |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    |     raise exc
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/app/backend/main.py", line 888, in check_url
    |     await get_all_models()
    |   File "/app/backend/main.py", line 928, in get_all_models
    |     pipe_models = await get_pipe_models()
    |                   ^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/app/backend/apps/webui/main.py", line 147, in get_pipe_models
    |     function_module = get_function_module(pipe.id)
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/app/backend/apps/webui/main.py", line 131, in get_function_module
    |     function_module, _, _ = load_function_module_by_id(pipe_id)
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/app/backend/apps/webui/utils.py", line 89, in load_function_module_by_id
    |     os.rename(function_path, f"{function_path}.error")
    | FileNotFoundError: [Errno 2] No such file or directory: '/app/backend/data/functions/langchain_pipe.py' -> '/app/backend/data/functions/langchain_pipe.py.error'
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/main.py", line 902, in update_embedding_function
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/main.py", line 888, in check_url
    await get_all_models()
  File "/app/backend/main.py", line 928, in get_all_models
    pipe_models = await get_pipe_models()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/apps/webui/main.py", line 147, in get_pipe_models
    function_module = get_function_module(pipe.id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/apps/webui/main.py", line 131, in get_function_module
    function_module, _, _ = load_function_module_by_id(pipe_id)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/apps/webui/utils.py", line 89, in load_function_module_by_id
    os.rename(function_path, f"{function_path}.error")
FileNotFoundError: [Errno 2] No such file or directory: '/app/backend/data/functions/langchain_pipe.py' -> '/app/backend/data/functions/langchain_pipe.py.error'
Error: The file /app/backend/data/functions/langchain_pipe.py does not exist.
```

**Screenshots/Screen Recordings (if applicable):**
N/A

## Additional Information

It avoids my open webui to start

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by Tavernari** [comment]
My idea to fix it is replacing the exception logic to use this instead:

```python
    except Exception as e:
        print(f"Error loading module: {function_id}")
        
        if os.path.exists(function_path):
            # Move the file to the error folder
            os.rename(function_path, f"{function_path}.error")
        else:
            print(f"Error: The file {function_path} does not exist.")
            # write the error to a file
            with open(f"{function_path}.error", "w") as file:
                file.write(str(e))
            
        raise e
 ```

**Comment by tjbck** [comment]
The code you mentioned no longer exists in the latest release.

**Comment by thiswillbeyourgithub** [comment]
FYI

I'm hitting this issue today using docker compose to build this image: `ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}-cuda`


It's completely stopping open-webui from running. To fix it I have added a file where it was missing.

```
open-webui  |   File "/app/backend/apps/webui/utils.py", line 89, in load_function_module_by_id
open-webui  |     os.rename(function_path, f"{function_path}.error")
open-webui  | FileNotFoundError: [Errno 2] No such file or directory: '/app/backend/data/functions/removethinking_clone.py' -> '/app/backend/data/functions/removethinking_clone.py.error'
```
