### ISSUE TITLE
Searxng web-search error: 

### ISSUE THREAD

**Issue by anonymousmaharaj** [open-webui/open-webui#5339]
# Bug Report

## Installation Method

I installed openwebui with helm chart - https://github.com/open-webui/helm-charts

## Environment

- **Open WebUI Version:** 
- v0.3.21

- **Operating System:** 
- macOS

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Searching with searxng has been successful

## Actual Behavior:

I got error
Something went wrong :/ [Errno -2] Name or service not known

## Description

**Bug Summary:**
ERROR [open_webui.apps.rag.main] [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/rag/main.py", line 933, in store_web_search
    loader = get_web_loader(urls)
             ^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/rag/main.py", line 753, in get_web_loader
    if not validate_url(url):
           ^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/rag/main.py", line 782, in validate_url
    return all(validate_url(u) for u in url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/rag/main.py", line 782, in <genexpr>
    return all(validate_url(u) for u in url)
               ^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/rag/main.py", line 771, in validate_url
    ipv4_addresses, ipv6_addresses = resolve_hostname(parsed_url.hostname)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/rag/main.py", line 789, in resolve_hostname
    addr_info = socket.getaddrinfo(hostname, None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 974, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

## Reproduction Details

**Steps to Reproduce:**
I deployed my searxng service in k8s and it is successfully accessible via https.
Add https://search.domain.pro/search?q=<query>

Activate Web-Search and he

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots/Screen Recordings (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by anonymousmaharaj** [comment]
This error occurs when a function string contains an address with http or https.

If you do not specify https in the web-ui itself, you will get another error - lack of scheme
Invalid URL 'search.domain.pro/search': No scheme supplied. Perhaps you meant https://search.domain.pro/search?

>>> resolve_hostname("search.domain.pro")
(['ip, 'ip', 'ip], [])


>>> resolve_hostname("https://search.domain.pro")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in resolve_hostname
  File "/usr/local/lib/python3.11/socket.py", line 974, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

**Comment by anonymousmaharaj** [comment]
Does this method validate_url check the urls of those sites that are returned as a response? 

I don't understand what can be done here.
