### ISSUE TITLE
'Internal Server Error' after update via Pip to v. 0.3.22 and 0.3.23 on Windows

### ISSUE THREAD

**Issue by akdengi** [open-webui/open-webui#5618]
# Bug Report

## Installation Method

Pip install on Windows

```
pip install --upgrade open-webui
```

## Environment

- v0.3.23
- Windows 11

## Description

When i am update Open Webui from v. 0.3.21 to 0.3.22 i see 
'Internal Server Error' when open in browser https://0.0.0.0:8080

Update to 0.3.23 not resolved my problem.

All works fine when i am revert to v. 0.3.21

On logs  i see that:

```
INFO:     127.0.0.1:56191 - "GET /favicon.ico HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_utils.py", line 87, in collapse_excgroups
  |     yield
  |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 190, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 401, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 123, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    |     raise exc
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 189, in __call__
    |     with collapse_excgroups():
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_utils.py", line 93, in collapse_excgroups
    |     raise exc
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\open_webui\main.py", line 850, in inspect_websocket
    |     return await call_next(request)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    |     raise app_exc
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 151, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 189, in __call__
    |     with collapse_excgroups():
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_utils.py", line 93, in collapse_excgroups
    |     raise exc
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\open_webui\main.py", line 829, in update_embedding_function
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    |     raise app_exc
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 151, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 189, in __call__
    |     with collapse_excgroups():
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_utils.py", line 93, in collapse_excgroups
    |     raise exc
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\open_webui\main.py", line 815, in check_url
    |     await get_all_models()
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\open_webui\main.py", line 873, in get_all_models
    |     pipe_models = await get_pipe_models()
    |                   ^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\open_webui\apps\webui\main.py", line 155, in get_pipe_models
    |     function_module = get_function_module(pipe.id)
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\open_webui\apps\webui\main.py", line 139, in get_function_module
    |     function_module, _, _ = load_function_module_by_id(pipe_id)
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\kazan\AppData\Local\Programs\Python\Python311\Lib\site-packages\open_webui\apps\webui\utils.py", line 160, in load_function_module_by_id
    |     os.unlink(temp_file.name)
    | PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'C:\\Users\\kazan\\AppData\\Local\\Temp\\tmpkosvor5s'
    +------------------------------------
```

**Comment by tjbck** [comment]
#5606
