### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'model_dump'

### ISSUE THREAD

**Issue by arsaboo** [open-webui/open-webui#6018]
## Installation Method

Docker

## Environment

- **Open WebUI Version:** v0.3.32
- **Ollama (if applicable):** 0.3.12

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

I am still seeing this error with 0.3.32:
```bash
ERROR [open_webui.apps.retrieval.utils] Error when querying the collection: 'NoneType' object has no attribute 'model_dump'
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/retrieval/utils.py", line 196, in query_collection
    results.append(result.model_dump())
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model_dump'
```

This is sometimes followed by another error:

```bash

INFO:     X.Y.Z.X:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=P9ieJ95&sid=KmUCneyS6NrGGLFvAAAL HTTP/1.1" 200 OK
post request handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/engineio/async_server.py", line 306, in handle_request
    await socket.handle_post_request(environ)
  File "/usr/local/lib/python3.11/site-packages/engineio/async_socket.py", line 109, in handle_post_request
    p = payload.Payload(encoded_payload=body)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/engineio/payload.py", line 13, in __init__
    self.decode(encoded_payload)
  File "/usr/local/lib/python3.11/site-packages/engineio/payload.py", line 44, in decode
    raise ValueError('Too many packets in payload')
ValueError: Too many packets in payload
ERROR [engineio.server] post request handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/engineio/async_server.py", line 306, in handle_request
    await socket.handle_post_request(environ)
  File "/usr/local/lib/python3.11/site-packages/engineio/async_socket.py", line 109, in handle_post_request
    p = payload.Payload(encoded_payload=body)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/engineio/payload.py", line 13, in __init__
    self.decode(encoded_payload)
  File "/usr/local/lib/python3.11/site-packages/engineio/payload.py", line 44, in decode
    raise ValueError('Too many packets in payload')
ValueError: Too many packets in payload
```

**Comment by tjbck** [comment]
Fixed on dev, testing wanted here!

**Comment by arsaboo** [comment]
I am still seeing error with `main`
```bash
ERROR [open_webui.apps.retrieval.utils] Error when querying the collection with hybrid_search: Collection file-144091f5-9fb5-41d3-9877-98cc3e7bca49 does not exist.
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/retrieval/utils.py", line 217, in query_collection_with_hybrid_search
    result = query_doc_with_hybrid_search(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/retrieval/utils.py", line 132, in query_doc_with_hybrid_search
    raise e
  File "/app/backend/open_webui/apps/retrieval/utils.py", line 94, in query_doc_with_hybrid_search
    result = VECTOR_DB_CLIENT.get(collection_name=collection_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/retrieval/vector/dbs/chroma.py", line 98, in get
    collection = self.client.get_collection(name=collection_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chromadb/api/client.py", line 142, in get_collection
    model = self._server.get_collection(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chromadb/api/segment.py", line 253, in get_collection
    raise InvalidCollectionException(f"Collection {name} does not exist.")
chromadb.errors.InvalidCollectionException: Collection file-144091f5-9fb5-41d3-9877-98cc3e7bca49 does not exist.
INFO  [open_webui.apps.ollama.main] generate_ollama_embeddings model='snowflake-arctic-embed:l' prompt='Team 1' options=None keep_alive=None
INFO  [open_webui.apps.ollama.main] url: http://host.docker.internal:11434
INFO  [open_webui.apps.ollama.main] generate_ollama_embeddings {'embedding': [0.26336926221847534, -1.5607023239135742, -0.8754041790962219, 0.8961717486381531, 0.009306579828262329, 0.41946420073509216, 
...
-0.385738730430603, 0.48370835185050964, 0.0031560808420181274]}
INFO  [open_webui.apps.retrieval.utils] query_doc:result None
ERROR [open_webui.apps.retrieval.utils] Error when querying the collection: 'NoneType' object has no attribute 'model_dump'
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/retrieval/utils.py", line 196, in query_collection
    results.append(result.model_dump())
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model_dump'```

With `dev`, I get the following error (and could not get the frontend loaded):

```bash
INFO  [open_webui.apps.openai.main] get_all_models()
ERROR [open_webui.apps.webui.routers.chats] (psycopg2.errors.UndefinedColumn) column tag.meta does not exist
LINE 1: ...tag.name AS tag_name, tag.user_id AS tag_user_id, tag.meta A...
                                                             ^
HINT:  Perhaps you meant to reference the column "tag.data".
[SQL: SELECT tag.id AS tag_id, tag.name AS tag_name, tag.user_id AS tag_user_id, tag.meta AS tag_meta 

 
WHERE tag.user_id = %(user_id_1)s]
[parameters: {'user_id_1': '9c7f822a-98ba-4fb6-9d84-0c8d87586ba7'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column tag.meta does not exist
LINE 1: ...tag.name AS tag_name, tag.user_id AS tag_user_id, tag.meta A...
                                                             ^
HINT:  Perhaps you meant to reference the column "tag.data".
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/webui/routers/chats.py", line 172, in get_all_user_tags
    tags = Tags.get_tags_by_user_id(user.id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/webui/models/tags.py", line 82, in get_tags_by_user_id
    for tag in (db.query(Tag).filter_by(user_id=user_id).all())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2673, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column tag.meta does not exist
LINE 1: ...tag.name AS tag_name, tag.user_id AS tag_user_id, tag.meta A...
                                                             ^
HINT:  Perhaps you meant to reference the column "tag.data".
[SQL: SELECT tag.id AS tag_id, tag.name AS tag_name, tag.user_id AS tag_user_id, tag.meta AS tag_meta 


WHERE tag.user_id = %(user_id_1)s]
[parameters: {'user_id_1': '9c7f822a-98ba-4fb6-9d84-0c8d87586ba7'}]
(Background on this error at: https://sqlalche.me/e/20/f405)```

**Comment by arsaboo** [comment]
@tjbck BTW....this error only appears with documents.
