### ISSUE TITLE
uv deps != pyproject.toml deps

### ISSUE THREAD

**Issue by techknowlogick** [open-webui/open-webui#6207]
# Bug Report

In attempting to resolve a bug, I'm running into with using open-webui packaged for NixOS
* googleapis-common-protos being reported as missing and preventing the app from starting because pyproject.toml is treated as the source of truth for deps instead of uv.lock https://github.com/NixOS/nixpkgs/pull/342865

Would you be able to add `googleapis-common-protos` to pyproject.toml? I'm able to open a PR if you prefer.

Ty for this project. It is great to have a localized environment to ensure data privacy while experimenting with various models.

## Installation Method

I used an ad-hoc `nix-shell` invocation to run app.

## Environment

- **Open WebUI Version:** 0.3.32
- **Ollama (if applicable):** [e.g., v0.2.0, v0.1.32-rc1]

- **Operating System:** NixOS Unstable
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

The app loads, and operates as expected

## Actual Behavior:

Fails to run due to missing import

## Reproduction Details

**Steps to Reproduce:**
```
$ nix-shell -p open-webui
$ open-webui serve
# get the error shown in logs below
```

## Logs and Screenshots

```
$ nix-shell -p open-webui
$ open-webui serve
Loading WEBUI_SECRET_KEY from file, not provided as an environment variable.
Loading WEBUI_SECRET_KEY from /Users/tklk/.webui_secret_key
Traceback (most recent call last):

  File "/nix/store/b6alyqvb9ljcbjs8vv6mxkmywrn4faqn-open-webui-0.3.8/bin/.open-webui-wrapped", line 9, in <module>
    sys.exit(app())
             ^^^^^

  File "/nix/store/b6alyqvb9ljcbjs8vv6mxkmywrn4faqn-open-webui-0.3.8/lib/python3.12/site-packages/open_webui/__init__.py", line 43, in serve
    import main  # we need set environment variables before importing main
    ^^^^^^^^^^^

  File "/nix/store/b6alyqvb9ljcbjs8vv6mxkmywrn4faqn-open-webui-0.3.8/lib/python3.12/site-packages/main.py", line 32, in <module>
    from apps.socket.main import sio, app as socket_app

  File "/nix/store/b6alyqvb9ljcbjs8vv6mxkmywrn4faqn-open-webui-0.3.8/lib/python3.12/site-packages/apps/socket/main.py", line 5, in <module>
    from apps.webui.models.users import Users

  File "/nix/store/b6alyqvb9ljcbjs8vv6mxkmywrn4faqn-open-webui-0.3.8/lib/python3.12/site-packages/apps/webui/models/users.py", line 9, in <module>
    from apps.webui.internal.db import Base, JSONField, Session, get_db

  File "/nix/store/b6alyqvb9ljcbjs8vv6mxkmywrn4faqn-open-webui-0.3.8/lib/python3.12/site-packages/apps/webui/internal/db.py", line 7, in <module>
    from apps.webui.internal.wrappers import register_connection

  File "/nix/store/b6alyqvb9ljcbjs8vv6mxkmywrn4faqn-open-webui-0.3.8/lib/python3.12/site-packages/apps/webui/internal/wrappers.py", line 9, in <module>
    from config import SRC_LOG_LEVELS

  File "/nix/store/b6alyqvb9ljcbjs8vv6mxkmywrn4faqn-open-webui-0.3.8/lib/python3.12/site-packages/config.py", line 6, in <module>
    import chromadb

  File "/nix/store/cskvcfhvzlhri8b5ki2xqnvwwbi9abc8-python3.12-chromadb-0.5.3/lib/python3.12/site-packages/chromadb/__init__.py", line 6, in <module>
    from chromadb.auth.token_authn import TokenTransportHeader

  File "/nix/store/cskvcfhvzlhri8b5ki2xqnvwwbi9abc8-python3.12-chromadb-0.5.3/lib/python3.12/site-packages/chromadb/auth/token_authn/__init__.py", line 24, in <module>
    from chromadb.telemetry.opentelemetry import (

  File "/nix/store/cskvcfhvzlhri8b5ki2xqnvwwbi9abc8-python3.12-chromadb-0.5.3/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 12, in <module>
    from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter

  File "/nix/store/v3wwa1z9brqy0wl4rc9dnj5p144y76di-python3.12-opentelemetry-exporter-otlp-proto-grpc-1.25.0/lib/python3.12/site-packages/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py", line 27, in <module>
    from opentelemetry.exporter.otlp.proto.grpc.exporter import (

  File "/nix/store/v3wwa1z9brqy0wl4rc9dnj5p144y76di-python3.12-opentelemetry-exporter-otlp-proto-grpc-1.25.0/lib/python3.12/site-packages/opentelemetry/exporter/otlp/proto/grpc/exporter.py", line 43, in <module>
    from google.rpc.error_details_pb2 import RetryInfo

ModuleNotFoundError: No module named 'google.rpc'
```

**Comment by tjbck** [comment]
PR Welcome!
