### ISSUE TITLE
bug: The new feature tiktoken gives "400: Unknown encoding" error with simple text files containing C# source code

### ISSUE THREAD

**Issue by alpilotx** [open-webui/open-webui#6403]
## Installation Method
Installed official docker image from ghcr.io/open-webui/open-webui:main

## Environment

- **Open WebUI Version:** v0.3.33 (released on 24th of October 2024)
- **Ollama (if applicable):** 0.3.12

## Description

- I switched to the new tiktoken text splitter to test it and after that, while uploading my documents ( simple text files containing C# source code) each of them failed with:
- 400: Unknown encoding . Plugins found: ['tiktoken_ext.openai_public'] tiktoken version: 0.8.0 (are you on latest?)
- When I disable tiktoken (switch back to "Default (character)", everything works as expected (and as it did with v0.3.32), and no errors are thrown.

## Reproduction Details
- under the Admin --> Settings --> Documents
- choose any embedding model 
- switch on tiktoken in the admin section
- go to Workspace --> Knowledge --> Create new "Knowledge".
- Add a simple flat text file (in my case containing some c# code), and get the error message immediately after upload. 
- "400: Unknown encoding . Plugins found: ['tiktoken_ext.openai_public'] tiktoken version: 0.8.0 (are you on latest?)"

An example file is uploaded for repro:
[Shared.zip](https://github.com/user-attachments/files/17523656/Shared.zip)

## Logs and Screenshots

Here is an example log from a test upload:

```

INFO  [open_webui.apps.webui.routers.files] file.content_type: application/octet-stream
INFO  [open_webui.apps.retrieval.main] save_docs_to_vector_db [Document(metadata={'source': '/app/backend/data/uploads/c3bf8146-e8c1-4bd1-b2dd-aa3730660fff_Shared.cs'}, page_content='using System;\nusing System.Collections.Generic;\nusing System.Linq;\nusing System.Text;\nusing System.Threading.Tasks;\n\nnamespace TestEnv2.PerformanceTests\n{\n    public class SharedEnv2Model\n    {\n        public string TestId { get; set; }\n        public int? TestCode { get; set; }\n        public string EmailAddress { get; set; }\n        public string Test2d { get; set; }\n    }\n}\n')] file-c3bf8146-e8c1-4bd1-b2dd-aa3730660fff
ERROR [open_webui.apps.retrieval.main] Unknown encoding .
Plugins found: ['tiktoken_ext.openai_public']
tiktoken version: 0.8.0 (are you on latest?)
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/retrieval/main.py", line 888, in process_file
    raise e
  File "/app/backend/open_webui/apps/retrieval/main.py", line 862, in process_file
    result = save_docs_to_vector_db(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/retrieval/main.py", line 669, in save_docs_to_vector_db
    text_splitter = TokenTextSplitter(
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_text_splitters/base.py", line 246, in __init__
    enc = tiktoken.get_encoding(encoding_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tiktoken/registry.py", line 79, in get_encoding
    raise ValueError(
ValueError: Unknown encoding .
Plugins found: ['tiktoken_ext.openai_public']
tiktoken version: 0.8.0 (are you on latest?)
ERROR [open_webui.apps.webui.routers.files] 400: Unknown encoding .
Plugins found: ['tiktoken_ext.openai_public']
tiktoken version: 0.8.0 (are you on latest?)
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/retrieval/main.py", line 888, in process_file
    raise e
  File "/app/backend/open_webui/apps/retrieval/main.py", line 862, in process_file
    result = save_docs_to_vector_db(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/retrieval/main.py", line 669, in save_docs_to_vector_db
    text_splitter = TokenTextSplitter(
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_text_splitters/base.py", line 246, in __init__
    enc = tiktoken.get_encoding(encoding_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tiktoken/registry.py", line 79, in get_encoding
    raise ValueError(
ValueError: Unknown encoding .
Plugins found: ['tiktoken_ext.openai_public']
tiktoken version: 0.8.0 (are you on latest?)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/webui/routers/files.py", line 71, in upload_file
    process_file(ProcessFileForm(file_id=id))
  File "/app/backend/open_webui/apps/retrieval/main.py", line 897, in process_file
    raise HTTPException(
fastapi.exceptions.HTTPException: 400: Unknown encoding .
Plugins found: ['tiktoken_ext.openai_public']
tiktoken version: 0.8.0 (are you on latest?)
ERROR [open_webui.apps.webui.routers.files] Error processing file: c3bf8146-e8c1-4bd1-b2dd-aa3730660fff
Collection file-c3bf8146-e8c1-4bd1-b2dd-aa3730660fff does not exist.
INFO:     10.11.72.39:58149 - "POST /api/v1/files/ HTTP/1.1" 200 OK
INFO  [open_webui.apps.retrieval.main] save_docs_to_vector_db [Document(metadata={'name': 'Shared.cs', 'created_by': '1a46349b-346f-4545-aae6-0c095669ee41', 'file_id': 'c3bf8146-e8c1-4bd1-b2dd-aa3730660fff', 'content_type': 'application/octet-stream', 'size': 399}, page_content='using System;\nusing System.Collections.Generic;\nusing System.Linq;\nusing System.Text;\nusing System.Threading.Tasks;\n\nnamespace TestEnv2.PerformanceTests\n{\n    public class SharedEnv2Model\n    {\n        public string TestId { get; set; }\n        public int? TestCode { get; set; }\n        public string EmailAddress { get; set; }\n        public string Test2d { get; set; }\n    }\n}\n')] 3bfc5f65-0dca-47a4-865a-5db6d7042b91
ERROR [open_webui.apps.retrieval.main] Unknown encoding .
Plugins found: ['tiktoken_ext.openai_public']
tiktoken version: 0.8.0 (are you on latest?)
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/retrieval/main.py", line 888, in process_file
    raise e
  File "/app/backend/open_webui/apps/retrieval/main.py", line 862, in process_file
    result = save_docs_to_vector_db(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/retrieval/main.py", line 669, in save_docs_to_vector_db
    text_splitter = TokenTextSplitter(
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_text_splitters/base.py", line 246, in __init__
    enc = tiktoken.get_encoding(encoding_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tiktoken/registry.py", line 79, in get_encoding
    raise ValueError(
ValueError: Unknown encoding .
Plugins found: ['tiktoken_ext.openai_public']
tiktoken version: 0.8.0 (are you on latest?)
Collection file-c3bf8146-e8c1-4bd1-b2dd-aa3730660fff does not exist.
INFO:     10.11.72.39:58149 - "POST /api/v1/knowledge/3bfc5f65-0dca-47a4-865a-5db6d7042b91/file/add HTTP/1.1" 400 Bad Request

```

**Comment by tjbck** [comment]
Fixed with the latest!
