### ISSUE TITLE
Login Error Since 0.3.33 (SQLite related?)

### ISSUE THREAD

**Issue by zpetkovic** [open-webui/open-webui#6461]
# Bug Report

## Installation Method

Docker

## Environment

- **Open WebUI Version:** 0.3.33 and newer
- **Ollama (if applicable):** /

- **Operating System:** Rocky Linux
- **Browser (if applicable):** Edge, Chrome

**Confirmation:**

- [x ] I have read and followed all the instructions provided in the README.md.
- [x ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [x ] I have included the Docker container logs.
- [x ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Upgrading open-webui should usually load my db and will work.

## Actual Behavior:
From version 0.3.33 login is impossible.

## Description

**Bug Summary:**
After upgrading to 0.3.33 (and newer, tried 0.3.34 and 0.3.35), it's not possible to log in neither as admin nor as regular user.
Login screen renders okay, but from there on, something seems to be wrong with SQLite

## Reproduction Details

**Steps to Reproduce:**
- Upgrade the existing 0.3.32 to a version higher than that

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
```bash
ERROR [open_webui.apps.webui.routers.chats] (sqlite3.OperationalError) no such column: tag.meta
[SQL: SELECT tag.id AS tag_id, tag.name AS tag_name, tag.user_id AS tag_user_id, tag.meta AS tag_meta 
FROM tag 
WHERE tag.user_id = ?]
[parameters: ('3c5a6036-bf11-40e5-a399-a9e8f1542bb7',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: tag.meta

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/backend/open_webui/apps/webui/routers/chats.py", line 233, in get_all_user_tags
    tags = Tags.get_tags_by_user_id(user.id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/apps/webui/models/tags.py", line 82, in get_tags_by_user_id
    for tag in (db.query(Tag).filter_by(user_id=user_id).all())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2673, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: tag.meta
[SQL: SELECT tag.id AS tag_id, tag.name AS tag_name, tag.user_id AS tag_user_id, tag.meta AS tag_meta 
FROM tag 
WHERE tag.user_id = ?]
[parameters: ('3c5a6036-bf11-40e5-a399-a9e8f1542bb7',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Screenshots/Screen Recordings (if applicable):**
This is what gets rendered.
<img width="1340" alt="image" src="https://github.com/user-attachments/assets/aa745b81-1560-42ac-9b2c-f489c9642b7c">

## Additional Information

- quite large database (800 MB)
- using SSO via Microsoft, as well as regular login
- connecting to LiteLLM instance in another container

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Seems like the database migration issue, could you also share the entire backend logs?

**Comment by zpetkovic** [comment]
Thanks for a blazing fast response,

here's the log:
```bash
Loading WEBUI_SECRET_KEY from file, not provided as an environment variable.
Generating WEBUI_SECRET_KEY
Loading WEBUI_SECRET_KEY from .webui_secret_key
/app/backend/open_webui
/app/backend
/app
Running migrations
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 6a39f3d8e55c -> 242a2047eae0, Update chat table
INFO  [open_webui.env] 'JWT_EXPIRES_IN' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_OLLAMA_API' loaded from the latest database entry
INFO  [open_webui.env] 'OLLAMA_BASE_URLS' loaded from the latest database entry
INFO  [open_webui.env] 'OPENAI_API_KEYS' loaded from the latest database entry
INFO  [open_webui.env] 'OPENAI_API_BASE_URLS' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_SIGNUP' loaded from the latest database entry
INFO  [open_webui.env] 'DEFAULT_LOCALE' loaded from the latest database entry
INFO  [open_webui.env] 'DEFAULT_MODELS' loaded from the latest database entry
INFO  [open_webui.env] 'DEFAULT_PROMPT_SUGGESTIONS' loaded from the latest database entry
INFO  [open_webui.env] 'DEFAULT_USER_ROLE' loaded from the latest database entry
INFO  [open_webui.env] 'USER_PERMISSIONS' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_MODEL_FILTER' loaded from the latest database entry
INFO  [open_webui.env] 'MODEL_FILTER_LIST' loaded from the latest database entry
INFO  [open_webui.env] 'WEBHOOK_URL' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_COMMUNITY_SHARING' loaded from the latest database entry
WARNI [open_webui.env] 

WARNING: CORS_ALLOW_ORIGIN IS SET TO '*' - NOT RECOMMENDED FOR PRODUCTION DEPLOYMENTS.

INFO  [open_webui.env] 'WEBUI_BANNERS' loaded from the latest database entry
INFO  [open_webui.env] 'SHOW_ADMIN_DETAILS' loaded from the latest database entry
INFO  [open_webui.env] 'TASK_MODEL' loaded from the latest database entry
INFO  [open_webui.env] 'TASK_MODEL_EXTERNAL' loaded from the latest database entry
INFO  [open_webui.env] 'TITLE_GENERATION_PROMPT_TEMPLATE' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_SEARCH_QUERY' loaded from the latest database entry
INFO  [open_webui.env] 'SEARCH_QUERY_GENERATION_PROMPT_TEMPLATE' loaded from the latest database entry
INFO  [open_webui.env] 'TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE' loaded from the latest database entry
INFO  [open_webui.env] 'CONTENT_EXTRACTION_ENGINE' loaded from the latest database entry
INFO  [open_webui.env] 'TIKA_SERVER_URL' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_TOP_K' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_RELEVANCE_THRESHOLD' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_RAG_HYBRID_SEARCH' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_EMBEDDING_ENGINE' loaded from the latest database entry
INFO  [open_webui.env] 'PDF_EXTRACT_IMAGES' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_EMBEDDING_MODEL' loaded from the latest database entry
INFO  [open_webui.env] Embedding model set: text-embedding-3-small
INFO  [open_webui.env] 'RAG_RERANKING_MODEL' loaded from the latest database entry
INFO  [open_webui.env] 'CHUNK_SIZE' loaded from the latest database entry
INFO  [open_webui.env] 'CHUNK_OVERLAP' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_TEMPLATE' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_OPENAI_API_BASE_URL' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_OPENAI_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'YOUTUBE_LOADER_LANGUAGE' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_RAG_WEB_SEARCH' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_WEB_SEARCH_ENGINE' loaded from the latest database entry
INFO  [open_webui.env] 'SEARXNG_QUERY_URL' loaded from the latest database entry
INFO  [open_webui.env] 'GOOGLE_PSE_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'GOOGLE_PSE_ENGINE_ID' loaded from the latest database entry
INFO  [open_webui.env] 'BRAVE_SEARCH_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'SERPSTACK_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'SERPSTACK_HTTPS' loaded from the latest database entry
INFO  [open_webui.env] 'SERPER_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'SERPLY_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'TAVILY_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'SEARCHAPI_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_WEB_SEARCH_RESULT_COUNT' loaded from the latest database entry
INFO  [open_webui.env] 'RAG_WEB_SEARCH_CONCURRENT_REQUESTS' loaded from the latest database entry
INFO  [open_webui.env] 'IMAGE_GENERATION_ENGINE' loaded from the latest database entry
INFO  [open_webui.env] 'ENABLE_IMAGE_GENERATION' loaded from the latest database entry
INFO  [open_webui.env] 'IMAGES_OPENAI_API_BASE_URL' loaded from the latest database entry
INFO  [open_webui.env] 'IMAGES_OPENAI_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'IMAGE_SIZE' loaded from the latest database entry
INFO  [open_webui.env] 'IMAGE_STEPS' loaded from the latest database entry
INFO  [open_webui.env] 'IMAGE_GENERATION_MODEL' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_STT_OPENAI_API_BASE_URL' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_STT_OPENAI_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_STT_ENGINE' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_STT_MODEL' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_OPENAI_API_BASE_URL' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_OPENAI_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_API_KEY' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_ENGINE' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_MODEL' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_VOICE' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_SPLIT_ON' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_AZURE_SPEECH_REGION' loaded from the latest database entry
INFO  [open_webui.env] 'AUDIO_TTS_AZURE_SPEECH_OUTPUT_FORMAT' loaded from the latest database entry
INFO  [open_webui.apps.audio.main] whisper_device_type: cpu
WARNI [chromadb.db.impl.sqlite] ⚠️ It looks like you upgraded from a version below 0.6 and could benefit from vacuuming your database. Run chromadb utils vacuum --help for more information.
WARNI [langchain_community.utils.user_agent] USER_AGENT environment variable not set, consider setting it to identify your requests.
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO  [open_webui.apps.openai.main] get_all_models()
INFO  [open_webui.apps.openai.main] get_all_models()
Error: (sqlite3.OperationalError) error in table chat after rename: duplicate column name: old_chat
[SQL: ALTER TABLE chat RENAME chat TO old_chat]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

  ___                    __        __   _     _   _ ___
 / _ \ _ __   ___ _ __   \ \      / /__| |__ | | | |_ _|
| | | | '_ \ / _ \ '_ \   \ \ /\ / / _ \ '_ \| | | || |
| |_| | |_) |  __/ | | |   \ V  V /  __/ |_) | |_| || |
 \___/| .__/ \___|_| |_|    \_/\_/ \___|_.__/ \___/|___|
      |_|


v0.3.35 - building the best open-source AI user interface.

https://github.com/open-webui/open-webui
```
And then after that the error pops up when I try to login.

**Comment by tjbck** [comment]
Updating from 0.3.32 correct? I'm attempting to reproduce this exact issue.
