### ISSUE TITLE
STT - Web API - not working

### ISSUE THREAD

**Issue by mowtschan** [open-webui/open-webui#6600]
# Bug Report

## Installation Method

docker compose

## Environment

- **Open WebUI Version:** [latest]

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

STT engine for Web API works.

## Actual Behavior:

ERROR: 'NoneType' object is not a mapping

## Description

**Bug Summary:**
STT engine for Web API doesn't work.

## Reproduction Details

**Steps to Reproduce:**
![web-api-issue](https://github.com/user-attachments/assets/ca195ead-61a4-4585-bd59-9d7b92572b4f)

## Logs and Screenshots

docker logs:
```
open-webui   | INFO  [open_webui.apps.audio.main] file.content_type: audio/wav
open-webui   | ERROR [open_webui.apps.audio.main] 'NoneType' object is not a mapping
open-webui   | Traceback (most recent call last):
open-webui   |   File "/app/backend/open_webui/apps/audio/main.py", line 526, in transcription
open-webui   |     return {**data, "filename": file_path}
open-webui   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui   | TypeError: 'NoneType' object is not a mapping
open-webui   | ERROR [open_webui.apps.audio.main] 400: [ERROR: 'NoneType' object is not a mapping]
open-webui   | Traceback (most recent call last):
open-webui   |   File "/app/backend/open_webui/apps/audio/main.py", line 526, in transcription
open-webui   |     return {**data, "filename": file_path}
open-webui   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui   | TypeError: 'NoneType' object is not a mapping
open-webui   |
open-webui   | During handling of the above exception, another exception occurred:
open-webui   |
open-webui   | Traceback (most recent call last):
open-webui   |   File "/app/backend/open_webui/apps/audio/main.py", line 529, in transcription
open-webui   |     raise HTTPException(
open-webui   | fastapi.exceptions.HTTPException: 400: [ERROR: 'NoneType' object is not a mapping]
open-webui   | transcribe /app/backend/data/cache/audio/transcriptions/0691714b-63ce-4a34-9f2c-6988e72a52ea.wav
```

console logs:
```
[Log] Recording started (RichTextInput.DcUu9IOU.js, line 43)
[Log] Recording stopped (RichTextInput.DcUu9IOU.js, line 43)
[Log] {detail: "[ERROR: 400: [ERROR: 'NoneType' object is not a mapping]]"} (index.CqbU8MTe.js, line 1)
[Log] SpeechRecognitionEvent {isTrusted: true, resultIndex: 0, results: SpeechRecognitionResultList, type: "result", target: webkitSpeechRecognition, …} (RichTextInput.DcUu9IOU.js, line 43)
[Log] Speech recognition turned off due to inactivity. (RichTextInput.DcUu9IOU.js, line 43)
[Log] recognition ended (RichTextInput.DcUu9IOU.js, line 43)
```

**Comment by tjbck** [comment]
Fixed on dev, Thanks!
