### ISSUE TITLE
new verstion can not build

### ISSUE THREAD

**Issue by JiangYeming** [open-webui/open-webui#7675]
✓ 163 modules transformed.
x Build failed in 6.10s
error during build:
[vite]: Rollup failed to resolve import "lowlight" from "E:/Project/Openui/src/lib/components/common/RichTextInput.svelte".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///E:/Project/Openui/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65589:17)
    at onRollupWarning (file:///E:/Project/Openui/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65621:5)
    at onwarn (file:///E:/Project/Openui/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65284:7)
    at file:///E:/Project/Openui/node_modules/rollup/dist/es/shared/node-entry.js:19475:13
    at Object.logger [as onLog] (file:///E:/Project/Openui/node_modules/rollup/dist/es/shared/node-entry.js:21201:9)
    at ModuleLoader.handleInvalidResolvedId (file:///E:/Project/Openui/node_modules/rollup/dist/es/shared/node-entry.js:20090:26)
    at file:///E:/Project/Openui/node_modules/rollup/dist/es/shared/node-entry.js:20048:26
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tjbck** [comment]
Check for duplicates first.
