### ISSUE TITLE
Kagi Search Error

### ISSUE THREAD

**Issue by freeload101** [open-webui/open-webui#7980]
# Bug Report
 
<3 all the work on OpenWeb UI !!

## Installation Method
https://github.com/freeload101/SCRIPTS/blob/master/Bash/OpenWebUI_Fast.bash

## Environment

**Open WebUI Version:** 
 ghcr.io/open-webui/open-webui:dev-cuda
 
**Ollama (if applicable):** 
ollama version is 0.5.4

**Operating System:**
OS Name	Microsoft Windows 11 Pro	
Version	10.0.22621 Build 22621	

**Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]
Version 126.0.6478.115 (Official Build) (64-bit)

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [X] I have included the browser console logs.
- [X] I have included the Docker container logs.
- [X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:
Kagi search work like google search works. even with google errors I can see the API key it uses but with Kagi I don't see it in the error

## Actual Behavior:
Red error box

## Description

**Bug Summary:**
Google search works but Kagi does not. Do I need the invite only API key or does it work with FAST api ? I have 25$ in credits on my account

## Reproduction Details

**Steps to Reproduce:**
Invoke any search 

## Logs and Screenshots
![{6C055F68-2F78-462F-A875-A06DCABB43A2}](https://github.com/user-attachments/assets/33824d42-f06f-46ac-8c83-2b5a668f83f3)

**Browser Console Logs:** 
[localhost_chrome_logs.har.txt](https://github.com/user-attachments/files/18214868/localhost_chrome_logs.har.txt)

**Docker Container Logs:**
```
ERROR [open_webui.routers.retrieval] 401 Client Error: Unauthorized for url: https://kagi.com/api/v0/search?q=weather+forecast+for+today&limit=6
Traceback (most recent call last):
  File "/app/backend/open_webui/routers/retrieval.py", line 1248, in process_web_search
    web_results = search_web(
                  ^^^^^^^^^^^
  File "/app/backend/open_webui/routers/retrieval.py", line 1146, in search_web
    return search_kagi(
           ^^^^^^^^^^^^
  File "/app/backend/open_webui/retrieval/web/kagi.py", line 31, in search_kagi
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://kagi.com/api/v0/search?q=weather+forecast+for+today&limit=6
INFO:     47.4.236.77:0 - "POST /api/v1/retrieval/process/web/search HTTP/1.1" 400 Bad Request
INFO:     47.4.236.77:0 - "POST /api/chat/completions HTTP/1.1" 200 OK
INFO:     47.4.236.77:0 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 OK
INFO  [open_webui.routers.openai] get_all_models()
INFO:     47.4.236.77:0 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 OK
INFO  [open_webui.routers.ollama] get_all_models()
Count of chats for tag 'general': 0
**Screenshots/Screen Recordings (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]
```

## Additional Information
If you need a key hit me up rmccurdy.com

**Comment by tjbck** [comment]
@erics118

**Comment by erics118** [comment]
See https://help.kagi.com/kagi/api/search.html The fastgpt api key will not work.
