### ISSUE TITLE
Problem of not being able to have multiple rounds of conversation using the openai interface

### ISSUE THREAD

**Issue by muzhi1991** [open-webui/open-webui#932]
When I use openai’s interface for multi-round conversations, I can’t initiate a request after a few rounds of conversations, and I get the following error：

chrome console log：
```
5.31442014.js:5 Uncaught (in promise) ReferenceError: OPENAI_API_BASE_URL is not defined
    at Y (5.31442014.js:5:2692)
    at 5.31442014.js:2:482
    at Array.map (<anonymous>)
    at ce (5.31442014.js:2:158)
    at Ee (5.31442014.js:1:7016)
```
why OPENAI_API_BASE_URL var not exists, The problem seems to occur with the following code：

https://github.com/open-webui/open-webui/blob/6df2505bf0352a7580b33f17ce6844afe04fb7be/src/routes/(app)/%2Bpage.svelte#L588

I don't know much about js, how do I fix it?

**Comment by justinh-rahb** [comment]
How many turns are we talking about? Are you using OpenAI API through LiteLLM?

**Comment by muzhi1991** [comment]
> How many turns are we talking about? Are you using OpenAI API through LiteLLM?
about 3 turns（3 request  2 response，block in third turns）
no use LiteLLM, I only set api-key in Connecttion Settings, choose gpt-3.5-turbo

**Comment by tjbck** [comment]
Unable to reproduce the issue, moving to disscussion.
